version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  web:
    build: ./backend
    volumes:
      - ./backend:/application
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db/mydatabase
    depends_on:
      - db
    networks:
      - backend-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  postgres_data:
